baseURL = 'https://pinecoder.dev'
languageCode = 'en-us'
title = 'Pinecoder blog'

# Use our plain, keyboard-scrollable code-block render hook (no highlighting).
[markup.highlight]
  codeFences = true

[params]
  [imageProcessing]
    [resize]
      [blogImages]
        anchor = "center"
        method = "fit"
        width = 800
        quality = 80