baseURL = 'https://pinecoder.dev'
languageCode = 'en-us'
title = 'Pinecoder blog'

# https://gohugo.io/getting-started/configuration-markup/#highlight
[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = true
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    # Use classes, so I can override if needed
    # hugo gen chromastyles --style=witchhazel > static/syntax.css
    noClasses = false
    noHl = true
    style = 'witchhazel'
    tabWidth = 2

[params]
  [imageProcessing]
    [resize]
      [blogImages]
        anchor = "center"
        method = "fit"
        width = 800
        quality = 80